WIP: new buildbot
freifunk-berlin/ansible pull request #30
Opened 2022-11-29 10:36 UTC by pktpls

2022-12-12 15:03 UTC, pktpls commented
This is now ready for review and a first deployment. (The ansible settings rendering needs to be fixed but that can be done during deploy, I'm really too lazy to set up a test host just for this.)

What does it do:
* Login with Github, being a member of freifunk-berlin gives you all the permissions
* Builds need to be triggered manually at the moment
* One meta builder for packages, one meta builder for images
* The meta builders start one actual build per package architecture, or per image target
* Builds run in rootless Podman containers
* The results end up in `<masterdir>/public_html/builds/<type>/<build-id>`
* Send notification to a matrix channel

What does it not (yet) do:
* Publish packages or images at the proper `public_html/{feed,stable,unstable}` directories
* Scheduled builds once a week
* Build on commit (it probably doesn't make much sense for us)

The definitions for package architectures and targets now live in the falter-packages and falter-builter (see falter-builter#122) repositories. It's a bit verbose perhaps, but it also means we don't have to redeploy Buildbot whenever a target or architecture is added.

Workers probably need to be set up new. All they need is a working rootless Podman installation. Fedora 36+ is recommended, but any other distro might work too.

2022-12-12 15:04 UTC, pktpls commented
> What does it not (yet) do:

The missing pieces can be added later - I think it's already in a state where we can deploy, and everyone can try it out and get used to it.

2022-12-12 17:50 UTC, Akira25 commented
Just had a quick look on this now and will make a proper review later on, but want to mention this:

I quite disagree, that login into github is an good idea. The former buildbot-setup worked with webhooks. On every push (merge-request) to the correspondent branch, the packagefeed got build.

If it was a release, the full imageset was built afterwards. If it was a snapshot, then only a subset of the images (the most-used targets) were generated.

I would really like to keep it this way. In my opinion, log in into Github is a security-issue which could be avoided easily by having the webhooks.

Furthermore, I find it more useful to have builds per commit: There are times, when there does not happen a commit for over a month. The solution we had for this before, was having builds on commits, but using a branch-stable-timer. This would start the build only, if there wasn't a push on the branch for more than x minutes.

2022-12-12 18:24 UTC, pktpls commented
Sure, we can do all that in follow-up PRs :+1: 

But you'll have to explain the security issue thing, I don't understand what you're saying there.

2022-12-13 15:00 UTC, pktpls commented on roles/buildbot/files/targets.py
> +                'for t in $(cat targets-%(prop:release)s.txt | grep -v "#" | grep . | cut -d" " -f2- | xargs -n1 echo | sort); do if ! cat broken-%(prop:release)s.txt | grep -F "$t" >/dev/null; then
These shell one-liners need documentation comments similar to the `podman run` invocation docs.

2022-12-14 11:48 UTC, Akira25 requested changes
Looks very promising to me. Thank you for all the effort so far.

Unfortunately there are some things that we should address, before deploying this. Anyway, I am looking forward for experimental deployment quite soon. :)

2022-12-14 11:48 UTC, Akira25 commented on roles/buildbot/files/packages.py
> +    pollInterval=60))
I would pretty much prefer a [post-receive-hook](https://docs.buildbot.net/latest/manual/configuration/changesources.html?highlight=gitpoller#change-hooks-http-notifications) over polling.

In my opinion there are some good reasons for that:
- modifications on the code base doesn't happen too often (maybe once a month or even less)
- If modifications happen, they happen in bunches (someone did find the time to review some pull requests :) )

So if we poll every 60 seconds for changes, it might happen that we start building already, but there are some other PRs to be merged later. Quite often, we have PRs that depend on each other, so that we might end up with disfunctional builds.

It would be really cool, if we could solve that by having a [branch-stable-timer](https://docs.buildbot.net/latest/manual/configuration/schedulers.html?highlight=branch%20stable%20timer#singlebranchscheduler). That way, we can avoid useless builds too.

on the old buildbot, it was set to 10 minutes. Mabe 15 minutes is even more sufficient.

2022-12-14 11:48 UTC, Akira25 commented on roles/buildbot/files/packages.py
> +    builderNames=["dummy/packages"]))
This should be adjusted for production, shouldn't it? :)

2022-12-14 11:48 UTC, Akira25 commented on roles/buildbot/files/packages.py
> +    workernames=["worker1", "worker2", "worker3", "worker4", "worker5", "worker6", "worker7", "worker8"],
Would be cool, If we could configure the workers on a somewhat central point, like it was before with the workers.py

2022-12-14 11:48 UTC, Akira25 commented on roles/buildbot/files/packages.py
> +    wwwurl = util.Interpolate("https://firmware.berlin.freifunk.net/%(kw:wwwpath)s", wwwpath=wwwpath)
Maybe it's a good Idea to have these configurable somewhere on a central place too. But I am not sure on that.

2022-12-14 11:48 UTC, Akira25 commented on roles/buildbot/files/packages.py
> +                tarfile=tarfile, wwwdir=wwwdir)]))
Interesting idea. Do you think its worth packaging and extracting the artifacts, though? If I remember right, all feeds together have around 30 MiB. So the uncompressed size of a feed could be around 1 MiB roughly.

Or did you maybe have other reasosn for doing this?

2022-12-14 11:48 UTC, Akira25 commented on roles/buildbot/files/asyncbuild.py
> +
The meaning of this class can get even clearer, if we add the link, you've mentioned in the beginning somewhere here in that files header. :)

https://github.com/buildbot/buildbot/issues/3088

2022-12-14 11:48 UTC, Akira25 commented on roles/buildbot/files/targets.py
> +    pollInterval=60))
As images or targets depend on having the recent packages, it would be maybe more useful, to set this builder in relation to a finished packages builder.

On the old buildbot, the last step of the feed-builder triggered the generation of the correspondent images. We could do it here too, maybe.

For snapshot builds we could nevertheless add an weekly scheduler, so the openWrt-basis gets updated regularly.

2022-12-14 11:48 UTC, Akira25 commented on roles/buildbot/files/targets.py
> +    workernames=["worker1", "worker2", "worker3", "worker4", "worker5", "worker6", "worker7", "worker8"],
As these are probably the same workers as for the feeds, it would be cool, to have this configured in a central place. maybe something similar to former workers.py.

2022-12-14 11:48 UTC, Akira25 commented on roles/buildbot/files/targets.py
> +                "podman run -i --rm --timeout=21600 --log-driver=none docker.io/library/alpine:edge sh -c '( apk add git bash wget xz coreutils build-base gcc abuild binutils ncurses-dev gawk bzip2 g
podman 3.0.1, which gets currently installed on the debian machines apparently does not know the `--timeout` option. Surely, we can fix this by installing a newer version. I just wnated to mention it for the records.

2022-12-18 11:25 UTC, rtznprmpftl commented on roles/buildbot/files/secrets.py.sample
> +dbURL = 'sqlite:///state.sqlite'
for context: sqlite would be still a viable option if the buildbot VM had enough IO, but the VM host IIRC only has 2x3,5" HDDs in there which makes it necessary to have a DB that keeps a lot in memory without relying on the linux pagecache.

2022-12-18 11:27 UTC, rtznprmpftl commented on roles/buildbot/files/secrets.py.sample
> +matrixAccessToken = 'CHANGE-ME'
i agree with akira, i  please use variables here

2022-12-20 01:16 UTC, Akira25 commented
There are some things I still want to address in this PR, therefor I switched it to draft. The current state is already deployed at buildbot.berlin.freifunk.net. If you like, take a look around. Really great work from @pktpls.

2022-12-27 02:22 UTC, pktpls commented on roles/buildbot/files/packages.py
> +                tarfile=tarfile, wwwdir=wwwdir)]))
The tarball is only for moving the artifacts out of the build container. This way we avoid filesystem permission problems. And since we already have a tarball, it's slightly easier to upload to the build master than a directory structure.

Afterwards the tarball gets discarded.

2022-12-27 04:50 UTC, pktpls commented on roles/buildbot/files/master.cfg
> +        room=matrixRoom))
Can be removed very easily, so let's keep it for now while we're actively working

2022-12-27 05:04 UTC, pktpls commented
I've done the commenting and formatting changes via rebasing. Thanks a lot @Akira25 for the deployment help!

I have a list of little things that can wait for other PRs (some issues and some opinions :>), but three things would be good to do first:

- [ ] Use an AnyBranchScheduler instead of the stuff copy-pasted from the old buildbot
- [ ] Remove `wget` call for falter version, we already have the correct git revision checked out, just read from the file :-)
- [ ] Move symlinking of releases to a separate PR, it has problems and can wait for the next round. I also think that copying into the final location might be better.

2022-12-27 08:57 UTC, Akira25 commented on roles/buildbot/files/packages.py
> +    builderNames=["dummy/packages"]))
I now got a better idea why it is called `dummy/packages`: This builder gets spawned for every architecture to parallelize the build. Neat solution.

2022-12-31 18:41 UTC, Akira25 submitted a review, later dismissed

2022-12-31 18:41 UTC, Akira25 commented
I think that schould do it now. :)

2023-01-01 13:24 UTC, Akira25 submitted a review, later dismissed

2023-01-01 13:40 UTC, Akira25 approved these changes

2023-01-01 13:44 UTC, Akira25 commented
Merging for pktpls. I removed this enerving auto-disapprove-rule too.

2023-01-01 13:44 UTC, merged