README: Add tutorial on buildbot-worker and change structure
freifunk-berlin/ansible pull request #70
Opened 2023-02-19 12:45 UTC by Akira25

This introduces a tutorial for adidng a buildbot worker to config management.

2023-02-19 14:03 UTC, Noki commented on Tutorials.md
> +asldkfj
gibberish..

2023-02-19 16:05 UTC, Akira25 commented on Tutorials.md
> +asldkfj
right. Adjusted in new commit.

2023-02-20 16:25 UTC, Noki requested changes

2023-02-20 16:25 UTC, Noki commented on Tutorials.md
> +For this stage, you need to access the machine as root user. Add the machine to the `hosts`-file and write it into the right section to tag its purpose. For defining a machine to serve as a buildbot
Describe that is required that you have checked out the repository at this point.

give the full path of the hosts file within the repository

2023-02-20 16:25 UTC, Noki commented on Tutorials.md
> +testmachine ansible_host=example.org
the buildbotworker is a bad example, as it is identical to the example below. choose another one.

2023-02-20 16:25 UTC, Noki commented on Tutorials.md
> +After that, just run the rest of the playbooks for the given machine, accessing it with your own ssh login: `ansible-playbook play.yml --limit=testmachine`.
This requires a .vaultpass file. This needs to be explained and should be listed as prerequirement.

2023-02-20 16:25 UTC, Noki commented on Tutorials.md
> +buildbot-worker-01 ansible_host=85.215.202.123
give multiple examples with comments:

```
buildbot-worker-01 ansible_host=85.215.202.123                  # reachable using a public IP
buildbot-worker-02 ansible_host=worker2.example.com             # reachable using a public host
buildbot-worker-akira ansible_host=192.168.16.7                 # reachable only from within martins home using a private IP
buildbot-worker-scherer8 ansible_host=scherer8-buildbot.olsr    # reachable only from within freifunk-net use a jump-host or so...
```

2023-02-20 16:25 UTC, Noki commented on Tutorials.md
> +For the `ansible_host` variable, you can give either a (public) IP Address our an hostname like `example.org`.
is the public IP/host really required?

2023-02-20 16:25 UTC, Noki commented on Tutorials.md
> +Please open `inventory/group_vars/all`. There you will find a list with all workers that are allowed to connect to the buildbot master.
This is encrypted. How do you edit it?

2023-02-20 16:25 UTC, Noki commented on Tutorials.md
> +1. Set up the users and basic installation
This is already done in a basic debian install, right? It automatically creates a user and a root account. Should you setup an additional user for the worker?

2023-02-28 19:54 UTC, Akira25 commented
@Noki I uploaded a new version, which hopefully clarifies things.

2023-02-28 19:54 UTC, Akira25 commented on Tutorials.md
> +In this file, you will find some tutorials describing common workflows for using this repo. We generally assume, that all Hosts run a recent stable Debian version (at time of writing: Debian 11). Our
Added in new version.

2023-02-28 19:54 UTC, Akira25 commented on README.md
> -## Tutorial for provisioning a new machine
Added in new version.

2023-02-28 19:55 UTC, Akira25 commented on Tutorials.md
> +For this stage, you need to access the machine as root user. Add the machine to the `hosts`-file and write it into the right section to tag its purpose. For defining a machine to serve as a buildbot
Added in new version.

2023-02-28 19:55 UTC, Akira25 commented on Tutorials.md
> +testmachine ansible_host=example.org
Addressed in new version.

2023-02-28 19:55 UTC, Akira25 commented on Tutorials.md
> +After that, just run the rest of the playbooks for the given machine, accessing it with your own ssh login: `ansible-playbook play.yml --limit=testmachine`.
It is in the general prerequisites now.

2023-02-28 19:55 UTC, Akira25 commented on Tutorials.md
> +buildbot-worker-01 ansible_host=85.215.202.123
Added.

2023-02-28 19:56 UTC, Akira25 commented on Tutorials.md
> +For the `ansible_host` variable, you can give either a (public) IP Address our an hostname like `example.org`.
It isn't. added.

2023-02-28 19:57 UTC, Akira25 commented on Tutorials.md
> +Please open `inventory/group_vars/all`. There you will find a list with all workers that are allowed to connect to the buildbot master.
The cannonical way of editing this, is to open it with `ansible-vaultpass edit $FILE`. This requires a `.vaultpass`-file though.

2023-02-28 19:59 UTC, Akira25 commented on Tutorials.md
> +1. Set up the users and basic installation
There is an additional user for the buildbot worker for improved security reasons, but it gets created by the buildbot-worker role itself. There is no need for further interaction with the machine except for running ansible.

2023-03-01 06:09 UTC, Noki commented
The toml formatting looks odd. I would probably change it to a standard code block and than this PR can be merged:
https://github.com/freifunk-berlin/ansible/blob/5010939bfb8634ffd68abd09751b2969ac9d465f/Tutorials.md#1-set-up-the-basic-installation
https://github.com/freifunk-berlin/ansible/blob/5010939bfb8634ffd68abd09751b2969ac9d465f/Tutorials.md#get-your-machine-known-to-ansible

2023-03-01 19:54 UTC, nicolasberens approved these changes

2023-03-02 22:49 UTC, Akira25 commented
Changed the strange looking markups. Merging due approval.

2023-03-03 08:12 UTC, Noki approved these changes

2023-03-03 08:12 UTC, merged