smaller fixes
freifunk-berlin/ansible pull request #88
Opened 2023-08-29 20:09 UTC by nicolasberens

a collection of my collected smaller fixes for the tunneldiger hosts.

(since i currently don't have a lot of time, i thought it might actually a good idea to bring this upstream before i forget this for another month )

2023-08-30 10:53 UTC, pmelange requested changes
I left a couple ideas for changes, but I will leave them up to you to decide if they should be made or not.

2023-08-30 10:53 UTC, pmelange commented on roles/tunneldigger/tasks/main.yml
>        - bridge-utils
With the new tunneldigger-broker setup, I don't think we need bridge-utils anymore.  But it also doesn't hurt to have the package installed on the systems.

2023-08-30 10:53 UTC, pmelange commented on roles/tunneldigger/tasks/main.yml
> +    cmd: "source {{ tunneldigger_path }}/env/bin/activate && cd {{ tunneldigger_path }}/broker && pip install --upgrade setuptools && python setup.py install"
according to https://github.com/wlanslovenija/tunneldigger/commit/f73e008717e8488640cc0bf247417b10f72ee879 we should be able to do a "pip installl" command instead of "python setup.py".  But since both will work, I will leave the choice to you.

2023-08-30 13:03 UTC, Akira25 approved these changes
Looks good to me. Would love to have Perrys notes processed before merging.

2023-08-31 18:58 UTC, nicolasberens commented on roles/tunneldigger/tasks/main.yml
> +    cmd: "source {{ tunneldigger_path }}/env/bin/activate && cd {{ tunneldigger_path }}/broker && pip install --upgrade setuptools && python setup.py install"
in the currently used version it does not work, but when we switch everything to v0.4.0 then we can change it

2023-08-31 18:59 UTC, merged